#!/bin/bash
./renameLSL.sh mod/regbooth-1.0/sloodle_mod_regbooth-1.0.lsl mod/regbooth-1.0/objects/default/assets/sloodle_mod_regbooth-1.0.lslp
./renameLSL.sh mod/furniture-1.0/object_scripts/presentation_seating.lslp mod/furniture-1.0/objects/default/assets/presentation_seating.lslp
./renameLSL.sh mod/furniture-1.0/object_scripts/chalkboard.lsl mod/furniture-1.0/objects/chalkboard/assets/chalkboard.lslp
./renameLSL.sh mod/furniture-1.0/object_scripts/sign.lsl mod/furniture-1.0/objects/sign/assets/sign.lslp
./renameLSL.sh mod/furniture-1.0/object_scripts/twitterwall.lsl mod/furniture-1.0/objects/twitterwall/assets/twitterwall.lslp
./renameLSL.sh mod/gaming-1.0/object_scripts/game_buzzer.lsl mod/gaming-1.0/objects/gamebuzzer/assets/game_buzzer.lslp
./renameLSL.sh mod/gaming-1.0/object_scripts/sharks/shark_artificial_intelligence.lslp mod/gaming-1.0/objects/shark/assets/shark_artificial_intelligence.lslp
./renameLSL.sh mod/gaming-1.0/object_scripts/sharks/shark_pool_surface.lslp mod/gaming-1.0/objects/sharkpool/assets/shark_pool_surface.lslp
./renameLSL.sh mod/gaming-1.0/object_scripts/sharks/bloodbath.lsl mod/gaming-1.0/objects/shark/assets/bloodbath.lslp
./renameLSL.sh mod/gaming-1.0/object_scripts/sharks/fricken_laser_beams.lsl mod/gaming-1.0/objects/shark/assets/fricken_laser_beams.lslp
./renameLSL.sh mod/gaming-1.0/object_scripts/sharks/movelikeashark.lsl mod/gaming-1.0/objects/shark/assets/movelikeashark.lslp
./renameLSL.sh mod/gaming-1.0/object_scripts/sharks/redbubbles.lsl mod/gaming-1.0/objects/shark/assets/redbubbles.lslp
./renameLSL.sh mod/set-1.0/sloodle_set_simple_configured_panel.lsl mod/set-1.0/objects/default/assets/sloodle_set_simple_configured_panel.lslp
./renameLSL.sh mod/set-1.0/sloodle_set_simple_door_handle.lsl mod/set-1.0/objects/default/assets/sloodle_set_simple_door_handle.lslp
./renameLSL.sh mod/set-1.0/sloodle_httpin_forwarder.lsl mod/set-1.0/objects/default/assets/sloodle_httpin_forwarder.lslp
./renameLSL.sh mod/set-1.0/rezzer_shared_media_open_in_browser_btn.lsl mod/set-1.0/objects/default/assets/rezzer_shared_media_open_in_browser_btn.lslp
./renameLSL.sh mod/set-1.0/sloodle_move_teller.lsl mod/set-1.0/objects/default/assets/sloodle_move_teller.lslp
./renameLSL.sh mod/set-1.0/sloodle_object_creator.lsl mod/set-1.0/objects/default/assets/sloodle_object_creator.lslp
./renameLSL.sh mod/set-1.0/sloodle_rez_status_confirmer.lsl mod/set-1.0/objects/default/assets/sloodle_rez_status_confirmer.lslp
./renameLSL.sh mod/set-1.0/sloodle_mod_set-1.0.lsl mod/set-1.0/objects/default/assets/sloodle_mod_set-1.0.lslp
./renameLSL.sh mod/set-1.0/rezzer_reset_btn.lsl mod/set-1.0/objects/default/assets/rezzer_reset_btn.lslp
./renameLSL.sh mod/set-1.0/sloodle_shared_media_setup.lsl mod/set-1.0/objects/default/assets/sloodle_shared_media_setup.lslp
./renameLSL.sh mod/set-1.0/sloodle_set_effects_simple.lsl mod/set-1.0/objects/default/assets/sloodle_set_effects_simple.lslp
./renameLSL.sh mod/set-1.0/sloodle_set_back_glow.lsl mod/set-1.0/objects/default/assets/sloodle_set_back_glow.lslp
./renameLSL.sh mod/set-1.0/sloodle_open_in_browser.lsl mod/set-1.0/objects/default/assets/sloodle_open_in_browser.lslp
./renameLSL.sh mod/set-1.0/sloodle_notecard_httpin.lsl mod/set-1.0/objects/default/assets/sloodle_notecard_httpin.lslp
./renameLSL.sh mod/set-1.0/sloodle_shared_media_screen.lsl mod/set-1.0/objects/default/assets/sloodle_shared_media_screen.lslp
./renameLSL.sh mod/set-1.0/sloodle_set_simple_mothership_handler.lsl mod/set-1.0/objects/default/assets/sloodle_set_simple_mothership_handler.lslp
./renameLSL.sh mod/set-1.0/sloodle_rezzer_object.lsl mod/set-1.0/objects/default/assets/sloodle_rezzer_object.lslp
./renameLSL.sh mod/set-1.0/sloodle_position_handler.lsl mod/set-1.0/objects/default/assets/sloodle_position_handler.lslp
./renameLSL.sh mod/set-1.0/sloodle_httpin_config_requester.lsl mod/set-1.0/objects/default/assets/sloodle_httpin_config_requester.lslp
./renameLSL.sh mod/set-1.0/sloodle_set_effects_mothership.lsl mod/set-1.0/objects/default/assets/sloodle_set_effects_mothership.lslp
./renameLSL.sh mod/set-1.0/sloodle_set_simple_door.lsl mod/set-1.0/objects/default/assets/sloodle_set_simple_door.lslp
./renameLSL.sh mod/set-1.0/sloodle_setup_notecard_httpin.lsl mod/set-1.0/objects/default/assets/sloodle_setup_notecard_httpin.lslp
./renameLSL.sh mod/set-1.0/sloodle_translation_set_en.lsl mod/set-1.0/objects/default/assets/sloodle_translation_set_en.lslp
./renameLSL.sh mod/primdrop-1.0/sloodle_mod_primdrop-1.0_FULL.lsl mod/primdrop-1.0/objects/default/assets/sloodle_mod_primdrop-1.0_FULL.lslp
./renameLSL.sh mod/primdrop-1.0/sloodle_primdrop_inventory.lsl mod/primdrop-1.0/objects/default/assets/sloodle_primdrop_inventory.lslp
./renameLSL.sh mod/primdrop-1.0/sloodle_mod_primdrop-1.0.lsl mod/primdrop-1.0/objects/default/assets/sloodle_mod_primdrop-1.0.lslp
./renameLSL.sh mod/primdrop-1.0/sloodle_mod_primdrop-1.0_world.lsl mod/primdrop-1.0/objects/default/assets/sloodle_mod_primdrop-1.0_world.lslp
./renameLSL.sh mod/regenrolbooth-1.0/sloodle_manual_reg_enrol.lsl mod/regenrolbooth-1.0/objects/default/assets/sloodle_manual_reg_enrol.lslp
./renameLSL.sh mod/regenrolbooth-1.0/sloodle_mod_regenrolbooth-1.0.lsl mod/regenrolbooth-1.0/objects/default/assets/sloodle_mod_regenrolbooth-1.0.lslp
./renameLSL.sh mod/distributor-1.0/sloodle_mod_distributor-1.0.lsl mod/distributor-1.0/objects/default/assets/sloodle_mod_distributor-1.0.lslp
./renameLSL.sh mod/glossary-1.0/sloodle_mod_glossary-1.0.lsl mod/glossary-1.0/objects/default/assets/sloodle_mod_glossary-1.0.lslp
./renameLSL.sh mod/glossary-1.0/sloodle_glossary_explainer.lsl mod/glossary-1.0/objects/default/assets/sloodle_glossary_explainer.lslp
./renameLSL.sh mod/choice-1.0/sloodle_mod_choice-1.0.lsl mod/choice-1.0/objects/default/assets/sloodle_mod_choice-1.0.lslp
./renameLSL.sh mod/choice-1.0/sloodle_choice_option.lsl mod/choice-1.0/objects/default/assets/sloodle_choice_option.lslp
./renameLSL.sh mod/choice-1.0/sloodle_choice_text.lsl mod/choice-1.0/objects/default/assets/sloodle_choice_text.lslp
./renameLSL.sh mod/choice-1.0/sloodle_choice_option_legend.lsl mod/choice-1.0/objects/default/assets/sloodle_choice_option_legend.lslp
./renameLSL.sh mod/scoreboard-1.0/object_scripts/zztext/active_light.lsl mod/scoreboard-1.0/objects/default/assets/active_light.lslp
./renameLSL.sh mod/scoreboard-1.0/object_scripts/zztext/_zztext_efficient_board_control.lsl mod/scoreboard-1.0/objects/default/assets/_zztext_efficient_board_control.lslp
./renameLSL.sh mod/scoreboard-1.0/object_scripts/zztext/zztext_scoreboard-1.0.lsl mod/scoreboard-1.0/objects/default/assets/zztext_scoreboard-1.0.lslp
./renameLSL.sh mod/scoreboard-1.0/object_scripts/zztext/btn_open_in_browser.lsl mod/scoreboard-1.0/objects/default/assets/btn_open_in_browser.lslp
./renameLSL.sh mod/scoreboard-1.0/sloodle_admin_animation.lsl mod/scoreboard-1.0/objects/default/assets/sloodle_admin_animation.lslp
./renameLSL.sh mod/scoreboard-1.0/sloodle_admin_hud.lsl mod/scoreboard-1.0/objects/default/assets/sloodle_admin_hud.lslp
./renameLSL.sh mod/scoreboard-1.0/sloodle_connect_button_anim.lsl mod/scoreboard-1.0/objects/default/assets/sloodle_connect_button_anim.lslp
./renameLSL.sh mod/scoreboard-1.0/sloodle_get_hud_button_anim.lsl mod/scoreboard-1.0/objects/default/assets/sloodle_get_hud_button_anim.lslp
./renameLSL.sh mod/scoreboard-1.0/sloodle_get_hud_button.lsl mod/scoreboard-1.0/objects/default/assets/sloodle_get_hud_button.lslp
./renameLSL.sh mod/scoreboard-1.0/sloodle_show_admin_button.lsl mod/scoreboard-1.0/objects/default/assets/sloodle_show_admin_button.lslp
./renameLSL.sh mod/scoreboard-1.0/sloodle_mod_scoreboard.lsl mod/scoreboard-1.0/objects/default/assets/sloodle_mod_scoreboard.lslp
./renameLSL.sh mod/scoreboard-1.0/sloodle_admin_control_panel.lsl mod/scoreboard-1.0/objects/default/assets/sloodle_admin_control_panel.lslp
./renameLSL.sh mod/scoreboard-1.0/sloodle_connect_button.lsl mod/scoreboard-1.0/objects/default/assets/sloodle_connect_button.lslp
./renameLSL.sh mod/scoreboard-1.0/sloodle_admin_hud_show_hide_button.lsl mod/scoreboard-1.0/objects/default/assets/sloodle_admin_hud_show_hide_button.lslp
./renameLSL.sh mod/presenter-2.0/sloodle_mod_presenter-2.0.lsl mod/presenter-2.0/objects/default/assets/sloodle_mod_presenter-2.0.lslp
./renameLSL.sh mod/presenter-2.0/sloodle_mod_presenter-shared-media-2.0.lsl mod/presenter-2.0/objects/default/assets/sloodle_mod_presenter-shared-media-2.0.lslp
./renameLSL.sh mod/accesscheckerdoor-1.0/sloodle_accesscheckerdoor_right.lsl mod/accesscheckerdoor-1.0/objects/default/assets/sloodle_accesscheckerdoor_right.lslp
./renameLSL.sh mod/accesscheckerdoor-1.0/sloodle_mod_accesscheckerdoor-1.0.lsl mod/accesscheckerdoor-1.0/objects/default/assets/sloodle_mod_accesscheckerdoor-1.0.lslp
./renameLSL.sh mod/accesscheckerdoor-1.0/sloodle_accesscheckerdoor_left.lsl mod/accesscheckerdoor-1.0/objects/default/assets/sloodle_accesscheckerdoor_left.lslp
./renameLSL.sh mod/picturegloss-1.0/sloodle_mod_glossary-1.0.lsl mod/picturegloss-1.0/objects/default/assets/sloodle_mod_glossary-1.0.lslp
./renameLSL.sh mod/picturegloss-1.0/sloodle_translation_picturegloss_en.lsl mod/picturegloss-1.0/objects/default/assets/sloodle_translation_picturegloss_en.lslp
./renameLSL.sh mod/pwreset-1.0/sloodle_mod_pwreset-1.0.lsl mod/pwreset-1.0/objects/default/assets/sloodle_mod_pwreset-1.0.lslp
./renameLSL.sh mod/presenter-1.0/sloodle_mod_presenter-1.0.lsl mod/presenter-1.0/objects/default/assets/sloodle_mod_presenter-1.0.lslp
./renameLSL.sh mod/presenter-1.0/sloodle_mod_presenter-1.0.lsl.os mod/presenter-1.0/objects/default/assets/sloodle_mod_presenter-1.0.lslp.os
./renameLSL.sh mod/building-1.0/object_scripts/hot_floor.lsl mod/building-1.0/objects/avatarclassroomfloors234/assets/hot_floor.lslp
./renameLSL.sh mod/accesschecker-1.0/sloodle_mod_accesschecker-1.0.lsl mod/accesschecker-1.0/objects/default/assets/sloodle_mod_accesschecker-1.0.lslp
./renameLSL.sh mod/accesschecker-1.0/sloodle_manual_reg_enrol.lsl mod/accesschecker-1.0/objects/default/assets/sloodle_manual_reg_enrol.lslp
./renameLSL.sh mod/demo-1.0/sloodle_mod_demo-1.0.lsl mod/demo-1.0/objects/default/assets/sloodle_mod_demo-1.0.lslp
./renameLSL.sh mod/distributor-2.0/object_scripts/vendor/sloodle_vendor.lsl mod/distributor-2.0/objects/default/assets/sloodle_vendor.lslp
./renameLSL.sh mod/enrolbooth-1.0/_setText.lsl mod/enrolbooth-1.0/objects/default/assets/_setText.lslp
./renameLSL.sh mod/enrolbooth-1.0/sloodle_mod_enrolbooth-1.0.lsl mod/enrolbooth-1.0/objects/default/assets/sloodle_mod_enrolbooth-1.0.lslp
./renameLSL.sh mod/loginzone-1.0/sloodle_mod_loginzone-1.0.lsl mod/loginzone-1.0/objects/default/assets/sloodle_mod_loginzone-1.0.lslp
./renameLSL.sh mod/quiz-1.0/sloodle_quiz_chair_poseball.lsl mod/quiz-1.0/objects/default/assets/sloodle_quiz_chair_poseball.lslp
./renameLSL.sh mod/quiz-1.0/sloodle_mod_quiz-1.0.lsl mod/quiz-1.0/objects/default/assets/sloodle_mod_quiz-1.0.lslp
./renameLSL.sh mod/quiz-1.0/sloodle_quiz_question_handler.lsl mod/quiz-1.0/objects/default/assets/sloodle_quiz_question_handler.lslp
./renameLSL.sh mod/quiz-1.0/sloodle_quiz_ui.lsl mod/quiz-1.0/objects/default/assets/sloodle_quiz_ui.lslp
./renameLSL.sh mod/moodlescreen-1.0/sloodle_moodle_screen.lsl mod/moodlescreen-1.0/objects/default/assets/sloodle_moodle_screen.lslp
./renameLSL.sh mod/interaction-1.0/object_scripts/zombie_move.lslp mod/interaction-1.0/objects/enemyrezzer/assets/zombie_move.lslp
./renameLSL.sh mod/interaction-1.0/object_scripts/sloodle_quiz_router.lslp mod/interaction-1.0/objects/enemyrezzer/assets/sloodle_quiz_router.lslp
./renameLSL.sh mod/interaction-1.0/object_scripts/well.lsl mod/interaction-1.0/objects/well/assets/well.lsl
./renameLSL.sh mod/interaction-1.0/object_scripts/anim_magic_chest.lslp mod/interaction-1.0/objects/magicchest/assets/anim_magic_chest.lslp
./renameLSL.sh mod/interaction-1.0/object_scripts/locked_door.lslp mod/interaction-1.0/objects/lockeddoor/assets/locked_door.lslp
./renameLSL.sh mod/interaction-1.0/object_scripts/magicplant.lslp mod/interaction-1.0/objects/magicplant/assets/magicplant.lslp
./renameLSL.sh mod/interaction-1.0/object_scripts/jellyfishswim.lslp mod/interaction-1.0/objects/jellyfish/assets/jellyfishswim.lslp
./renameLSL.sh mod/interaction-1.0/object_scripts/setAlpha.lslp mod/interaction-1.0/objects/jellyfish/assets/setAlpha.lslp
./renameLSL.sh mod/interaction-1.0/object_scripts/teleporter.lslp mod/interaction-1.0/objects/teleporter/assets/teleporter.lslp
./renameLSL.sh mod/interaction-1.0/object_scripts/zombie.lslp mod/interaction-1.0/objects/enemyrezzer/assets/zombie.lslp
./renameLSL.sh mod/interaction-1.0/object_scripts/enemy.lslp mod/interaction-1.0/objects/enemyrezzer/assets/enemy.lslp
./renameLSL.sh mod/interaction-1.0/object_scripts/teleporter_using_crystals_for_opensim.lsl mod/interaction-1.0/objects/crystalteleporter/assets/teleporter_using_crystals_for_opensim.lslp
./renameLSL.sh mod/interaction-1.0/object_scripts/blue_crystal_mover.lslp mod/interaction-1.0/objects/crystalteleporter/assets/blue_crystal_mover.lslp
./renameLSL.sh mod/interaction-1.0/object_scripts/magicchest.lslp mod/interaction-1.0/objects/magicchest/assets/magicchest.lslp
./renameLSL.sh mod/interaction-1.0/object_scripts/sloodle_quiz_ui_enemy.lslp mod/interaction-1.0/objects/enemyrezzer/assets/sloodle_quiz_ui_enemy.lslp
./renameLSL.sh mod/interaction-1.0/object_scripts/touchobject.lsl mod/interaction-1.0/objects/default/assets/touchobject.lsl
./renameLSL.sh mod/interaction-1.0/object_scripts/zombieEnemy.lslp mod/interaction-1.0/objects/enemyrezzer/assets/zombieEnemy.lslp
./renameLSL.sh mod/interaction-1.0/object_scripts/sloodle_rezzer_object_with_external_cleanup.lslp mod/interaction-1.0/objects/default/assets/sloodle_rezzer_object_with_external_cleanup.lslp
./renameLSL.sh mod/interaction-1.0/object_scripts/teleporter_using_crystals.lsl mod/interaction-1.0/objects/teleporter/assets/teleporter_using_crystals.lslp
./renameLSL.sh mod/interaction-1.0/sloodle_mod_touchable-1.0.lsl mod/interaction-1.0/objects/touchobject/assets/sloodle_mod_touchable-1.0.lslp
./renameLSL.sh mod/quiz_pile_on-1.0/sloodle_quiz_pile_on_choice.lsl mod/quiz_pile_on-1.0/objects/default/assets/sloodle_quiz_pile_on_choice.lslp
./renameLSL.sh mod/quiz_pile_on-1.0/sloodle_mod_quiz_pile_on-1.0.lsl mod/quiz_pile_on-1.0/objects/default/assets/sloodle_mod_quiz_pile_on-1.0.lslp
./renameLSL.sh mod/chat-1.0/sloodle_mod_chat-1.0.lsl.os mod/chat-1.0/objects/default/assets/sloodle_mod_chat-1.0.lslp.os
./renameLSL.sh mod/chat-1.0/sloodle_mod_chat-1.0.lsl mod/chat-1.0/objects/default/assets/sloodle_mod_chat-1.0.lslp
./renameLSL.sh mod/tracker-1.0/sloodle_mod_tracker-1.0.lsl mod/tracker-1.0/objects/default/assets/sloodle_mod_tracker-1.0.lslp
./renameLSL.sh mod/tracker-1.0/sloodle_tracker_scanner.lsl mod/tracker-1.0/objects/scanner/assets/sloodle_tracker_scanner.lslp
./renameLSL.sh mod/tracker-1.0/sloodle_tracker_button.lsl mod/tracker-1.0/objects/default/assets/sloodle_tracker_button.lslp
./renameLSL.sh lib/lsl/sloodle_reset_button.lsl assets/buttons/sloodle_reset_button.lslp
./renameLSL.sh lib/lsl/mem_array.lsl assets/misc/mem_array.lslp
./renameLSL.sh lib/lsl/sloodle_open_in_browser.lsl assets/buttons/sloodle_open_in_browser.lslp
./renameLSL.sh lib/lsl/memory_controller.lsl assets/misc/memory_controller.lslp
./renameLSL.sh lib/lsl/error_messages.lsl assets/misc/error_messages.lslp
./renameLSL.sh lib/lsl/sloodle_status_codes.lsl assets/misc/sloodle_status_codes.lslp
./renameLSL.sh toolbar/lsl/sloodle_blog_channel_display.lsl mod/toolbar_giver-1.0/objects/toolbar/assets/sloodle_blog_channel_display.lslp
./renameLSL.sh toolbar/lsl/sloodle_blog_hud.lsl mod/toolbar_giver-1.0/objects/toolbar/assets/sloodle_blog_hud.lslp
./renameLSL.sh toolbar/lsl/toolbar-menu.lsl mod/toolbar_giver-1.0/objects/toolbar/assets/toolbar-menu.lslp
./renameLSL.sh toolbar/lsl/blog_length_meter.lsl mod/toolbar_giver-1.0/objects/toolbar/assets/blog_length_meter.lslp
./renameLSL.sh toolbar/lsl/sloodle_avilister.lsl mod/toolbar_giver-1.0/objects/toolbar/assets/sloodle_avilister.lslp
./renameLSL.sh toolbar/lsl/toolbar-menu.lsl.os mod/toolbar_giver-1.0/objects/toolbar/assets/toolbar-menu.lslp.os
./renameLSL.sh toolbar/lsl/sloodle_blog_visibility_display.lsl mod/toolbar_giver-1.0/objects/toolbar/assets/sloodle_blog_visibility_display.lslp
./renameLSL.sh toolbar/lsl/sloodle_blog_ready_display.lsl mod/toolbar_giver-1.0/objects/toolbar/assets/sloodle_blog_ready_display.lslp
./renameLSL.sh toolbar/lsl/sloodle_toolbar_giver.lsl mod/toolbar_giver-1.0/objects/toolbar/assets/sloodle_toolbar_giver.lslp
./renameLSL.sh lsl/sloodle_parallel_url_loader_1.lsl assets/sloodle_parallel_url_loader_1.lslp
./renameLSL.sh lsl/sloodle_url_loader.lsl assets/sloodle_url_loader.lslp
./renameLSL.sh lsl/sloodle_parallel_url_loader_x.lsl assets/sloodle_parallel_url_loader_x.lslp
./renameLSL.sh lsl/sloodle_setup_notecard.lsl assets/sloodle_setup_notecard.lslp
./renameLSL.sh lsl/sloodle_parallel_url_loader_3.lsl assets/sloodle_parallel_url_loader_3.lslp
./renameLSL.sh lsl/sloodle_setup_web.lsl assets/sloodle_setup_web.lslp
./renameLSL.sh lsl/sloodle_hover_text_displayer.lsl assets/sloodle_hover_text_displayer.lslp
./renameLSL.sh lsl/sloodle_layout_object.lsl assets/sloodle_layout_object.lslp
./renameLSL.sh lsl/sloodle_email_login_details.lsl assets/sloodle_email_login_details.lslp
./renameLSL.sh lsl/xytext/xytext.lsl.16 assets/xytext/xytext.lslp.16
./renameLSL.sh lsl/xytext/xytext.lsl.24 assets/xytext/xytext.lslp.24
./renameLSL.sh lsl/xytext/xytext.lsl.4 assets/xytext/xytext.lslp.4
./renameLSL.sh lsl/xytext/xytext.lsl.13 assets/xytext/xytext.lslp.13
./renameLSL.sh lsl/xytext/xytext.lsl.15 assets/xytext/xytext.lslp.15
./renameLSL.sh lsl/xytext/xytext.lsl.14 assets/xytext/xytext.lslp.14
./renameLSL.sh lsl/xytext/xytext.lsl.1 assets/xytext/xytext.lslp.1
./renameLSL.sh lsl/xytext/xytext.lsl.10 assets/xytext/xytext.lslp.10
./renameLSL.sh lsl/xytext/xytext.lsl.8 assets/xytext/xytext.lslp.8
./renameLSL.sh lsl/xytext/xytext.lsl.17 assets/xytext/xytext.lslp.17
./renameLSL.sh lsl/xytext/xytext.lsl.23 assets/xytext/xytext.lslp.23
./renameLSL.sh lsl/xytext/xytext.lsl.3 assets/xytext/xytext.lslp.3
./renameLSL.sh lsl/xytext/xytext.lsl.5 assets/xytext/xytext.lslp.5
./renameLSL.sh lsl/xytext/xytext.lsl.22 assets/xytext/xytext.lslp.22
./renameLSL.sh lsl/xytext/xytext.lsl.21 assets/xytext/xytext.lslp.21
./renameLSL.sh lsl/xytext/xytext.lsl.20 assets/xytext/xytext.lslp.20
./renameLSL.sh lsl/xytext/xytext.lsl.12 assets/xytext/xytext.lslp.12
./renameLSL.sh lsl/xytext/xytext.lsl.18 assets/xytext/xytext.lslp.18
./renameLSL.sh lsl/xytext/xytext.lsl.19 assets/xytext/xytext.lslp.19
./renameLSL.sh lsl/xytext/xytext.lsl.7 assets/xytext/xytext.lslp.7
./renameLSL.sh lsl/xytext/xytext.lsl.11 assets/xytext/xytext.lslp.11
./renameLSL.sh lsl/xytext/xytext.lsl.2 assets/xytext/xytext.lslp.2
./renameLSL.sh lsl/xytext/xytext.lsl.6 assets/xytext/xytext.lslp.6
./renameLSL.sh lsl/xytext/xytext.lsl.9 assets/xytext/xytext.lslp.9
./renameLSL.sh lsl/sloodle_setup_user.lsl assets/misc/sloodle_setup_user.lslp
./renameLSL.sh lsl/sloodle_parallel_url_loader_2.lsl assets/misc/sloodle_parallel_url_loader_2.lsl
./renameLSL.sh lsl/sloodle_manual_reg_enrol.lsl assets/misc/sloodle_manual_reg_enrol.lsl
./renameLSL.sh lsl/sloodle_multi_url_loader.lsl assets/misc/sloodle_multi_url_loader.lslp
./renameLSL.sh lsl/sloodle_error_message_handler.lsl assets/misc/sloodle_error_message_handler.lslp
./renameLSL.sh lsl/sloodle_parallel_url_loader_0.lsl assets/misc/sloodle_parallel_url_loader_0.lslp
./renameLSL.sh lang/en/sloodle_translation_choice_en.lsl mod/choice-1.0/objects/default/assets/lang/en/sloodle_translation_choice_en.lslp
./renameLSL.sh lang/en/sloodle_translation_pwreset_en.lsl mod/pwreset-1.0/objects/default/assets/lang/en/sloodle_translation_pwreset_en.lslp
./renameLSL.sh lang/en/sloodle_translation_quiz_pile_on_en.lsl mod/quiz_pile_on-1.0/objects/default/assets/lang/en/sloodle_translation_quiz_pile_on_en.lslp
./renameLSL.sh lang/en/sloodle_translation_presenter_en.lsl mod/presenter-1.0/objects/default/assets/lang/en/sloodle_translation_presenter_en.lslp
./renameLSL.sh lang/en/sloodle_translation_en.lsl assets/lang/en/sloodle_translation_en.lslp
./renameLSL.sh lang/en/sloodle_translation_regenrol_en.lsl mod/regenrolbooth-1.0/objects/default/assets/lang/en/sloodle_translation_regenrol_en.lslp
./renameLSL.sh lang/en/sloodle_translation_quiz_en.lsl mod/quiz-1.0/objects/default/assets/lang/en/sloodle_translation_quiz_en.lslp
./renameLSL.sh lang/en/sloodle_translation_toolbar_en.lsl mod/toolbar_giver-1.0/objects/default/assets/lang/en/sloodle_translation_toolbar_en.lslp
./renameLSL.sh lang/en/sloodle_translation_metagloss_en.lsl mod/glossary-1.0/objects/default/assets/lang/en/sloodle_translation_metagloss_en.lslp
./renameLSL.sh lang/en/sloodle_translation_webintercom_en.lsl mod/chat-1.0/objects/default/assets/lang/en/sloodle_translation_webintercom_en.lslp
./renameLSL.sh lang/en/sloodle_translation_distributor_en.lsl mod/distributor-1.0/objects/default/assets/lang/en/sloodle_translation_distributor_en.lslp
./renameLSL.sh lang/en/sloodle_translation_avilister_en.lsl mod/toolbar_giver-1.0/objects/default/assets/lang/en/sloodle_translation_avilister_en.lslp
./renameLSL.sh lang/en/sloodle_translation_assignment_en.lsl mod/primdrop-1.0/objects/default/assets/lang/en/sloodle_translation_assignment_en.lslp
./renameLSL.sh lang/en/sloodle_translation_set_en.lsl mod/set-1.0/objects/default/assets/lang/en/sloodle_translation_set_en.lslp
./renameLSL.sh lang/fr_utf8/sloodle_translation_toolbar_fr.lsl mod/toolbar_giver-1.0/objects/default/assets/lang/fr/sloodle_translation_toolbar_fr.lslp
./renameLSL.sh lang/en_utf8/sloodle_translation_choice_en.lsl mod/choice-1.0/objects/default/assets/lang/en/sloodle_translation_choice_en.lslp
./renameLSL.sh lang/en_utf8/sloodle_translation_pwreset_en.lsl mod/pwreset-1.0/objects/default/assets/lang/en/sloodle_translation_pwreset_en.lslp
./renameLSL.sh lang/en_utf8/sloodle_translation_quiz_pile_on_en.lsl mod/quiz_pile_on-1.0/objects/default/assets/lang/en/sloodle_translation_quiz_pile_on_en.lslp
./renameLSL.sh lang/en_utf8/sloodle_translation_presenter_en.lsl mod/presenter-1.0/objects/default/assets/lang/en/sloodle_translation_presenter_en.lslp
./renameLSL.sh lang/en_utf8/sloodle_translation_en.lsl assets/lang/en/sloodle_translation_en.lslp
./renameLSL.sh lang/en_utf8/sloodle_translation_regenrol_en.lsl mod/regenrolbooth-1.0/objects/default/assets/lang/en/sloodle_translation_regenrol_en.lslp
./renameLSL.sh lang/en_utf8/sloodle_translation_quiz_en.lsl mod/quiz-1.0/objects/default/assets/lang/en/sloodle_translation_quiz_en.lslp
./renameLSL.sh lang/en_utf8/sloodle_translation_toolbar_en.lsl mod/toolbar_giver-1.0/objects/default/assets/lang/en/sloodle_translation_toolbar_en.lslp
./renameLSL.sh lang/en_utf8/sloodle_translation_metagloss_en.lsl mod/glossary-1.0/objects/default/assets/lang/en/sloodle_translation_metagloss_en.lslp
./renameLSL.sh lang/en_utf8/sloodle_translation_webintercom_en.lsl mod/chat-1.0/objects/default/assets/lang/en/sloodle_translation_webintercom_en.lslp
./renameLSL.sh lang/en_utf8/sloodle_translation_distributor_en.lsl mod/distributor-1.0/objects/default/assets/lang/en/sloodle_translation_distributor_en.lslp
./renameLSL.sh lang/en_utf8/sloodle_translation_avilister_en.lsl mod/toolbar_giver-1.0/objects/default/assets/lang/en/sloodle_translation_avilister_en.lslp
./renameLSL.sh lang/en_utf8/sloodle_translation_assignment_en.lsl mod/primdrop-1.0/objects/default/assets/lang/en/sloodle_translation_assignment_en.lslp
./renameLSL.sh lang/en_utf8/sloodle_translation_set_en.lsl mod/set-1.0/objects/default/assets/lang/en/sloodle_translation_set_en.lslp
./renameLSL.sh lang/fr/sloodle_translation_toolbar_fr.lsl mod/toolbar_giver-1.0/objects/default/assets/lang/fr/sloodle_translation_toolbar_fr.lslp


